# -*- coding: utf-8 -*-
"""Lenguajes Formales Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VN-txBebZ2hB_dMev82oMZfDtwGABWfp
"""

# LEXER (Analizador Lexico)


TOKENS = {
    'rule', 'if', 'then', 'AND',
    '>', '<', '=', ':',
    'ID', 'NUM', 'EOF'
}

def lexer(texto):
    """
    Recibe un string con el programa y devuelve una lista de tokens.
    Cada token es una tupla (tipo, valor).
    Ejemplo: ('ID', 'temp'), ('NUM', '35'), ('>', '>')
    """
    tokens = []
    i = 0
    palabras_clave = {'rule', 'if', 'then', 'AND'}

    while i < len(texto):
        c = texto[i]


        if c in (' ', '\t', '\n', '\r'):
            i += 1
            continue


        if c in ('>', '<', ':', ):
            tokens.append((c, c))
            i += 1
            continue


        if c == '=':
            tokens.append(('=', '='))
            i += 1
            continue


        if c.isdigit():
            num = ''
            while i < len(texto) and texto[i].isdigit():
                num += texto[i]
                i += 1
            tokens.append(('NUM', int(num)))
            continue


        if c.isalpha() or c == '_':
            palabra = ''
            while i < len(texto) and (texto[i].isalnum() or texto[i] == '_'):
                palabra += texto[i]
                i += 1
            if palabra in palabras_clave:
                tokens.append((palabra, palabra))
            else:
                tokens.append(('ID', palabra))
            continue


        i += 1

    tokens.append(('EOF', 'EOF'))
    return tokens



# PARSER (Analizador Sintactico) - LR(1) estilo descendente


class Parser:
    """
    Parser recursivo descendente.
    Sigue la gramatica del proyecto (transformada para evitar ambiguedad).
    """

    def __init__(self, tokens):
        self.tokens = tokens
        self.pos = 0

    def token_actual(self):
        return self.tokens[self.pos]

    def consumir(self, tipo_esperado):
        """Consume el token actual si coincide con el tipo esperado."""
        tipo, valor = self.token_actual()
        if tipo == tipo_esperado:
            self.pos += 1
            return valor
        else:
            raise SyntaxError(
                f"Se esperaba '{tipo_esperado}' pero se encontro '{tipo}' ({valor}) en posicion {self.pos}"
            )

    def parsear_programa(self):
        """
        Program -> RuleList
        Devuelve una lista de reglas (el AST del programa).
        """
        reglas = []
        while self.token_actual()[0] == 'rule':
            regla = self.parsear_regla()
            reglas.append(regla)
        self.consumir('EOF')
        return reglas

    def parsear_regla(self):
        """
        Rule -> rule id : if Cond then Action
        Devuelve un dict representando la regla (nodo del AST).
        """
        self.consumir('rule')
        nombre = self.consumir('ID')
        self.consumir(':')
        self.consumir('if')
        condicion = self.parsear_condicion()
        self.consumir('then')
        accion = self.consumir('ID')


        return {
            'tipo': 'Rule',
            'nombre': nombre,
            'condicion': condicion,
            'accion': accion
        }

    def parsear_condicion(self):
        """
        Cond -> Atom (AND Atom)*
        Devuelve el nodo AST de la condicion.
        Maneja multiples AND de forma iterativa para evitar recursion izquierda.
        """
        izq = self.parsear_atomo()


        while self.token_actual()[0] == 'AND':
            self.consumir('AND')
            der = self.parsear_atomo()
            izq = {
                'tipo': 'And',
                'izq': izq,
                'der': der
            }

        return izq

    def parsear_atomo(self):
        """
        Atom -> id RelOp value | id
        Devuelve nodo AST de tipo Cmp o Fact.
        """
        nombre = self.consumir('ID')


        tipo_sig = self.token_actual()[0]
        if tipo_sig in ('>', '<', '='):
            operador = self.token_actual()[0]
            self.pos += 1
            valor = self.consumir('NUM')
            return {
                'tipo': 'Cmp',
                'id': nombre,
                'op': operador,
                'valor': valor
            }
        else:
            # Es un hecho (fact)
            return {
                'tipo': 'Fact',
                'id': nombre
            }



# Interprete / Evaluador



def evaluar_condicion(condicion, variables, hechos):
    """
    Evalua recursivamente un nodo de condicion del AST.
    Retorna True o False.
    """
    tipo = condicion['tipo']

    if tipo == 'And':
        return (evaluar_condicion(condicion['izq'], variables, hechos) and
                evaluar_condicion(condicion['der'], variables, hechos))

    elif tipo == 'Cmp':
        id_var = condicion['id']
        op = condicion['op']
        val = condicion['valor']


        if id_var not in variables:
            return False

        valor_var = variables[id_var]

        if op == '>':
            return valor_var > val
        elif op == '<':
            return valor_var < val
        elif op == '=':
            return valor_var == val

    elif tipo == 'Fact':
        return condicion['id'] in hechos

    return False


def ejecutar_programa(reglas, variables, hechos_iniciales):
    """
    Ejecuta el programa usando el modelo de punto fijo.
    Repite hasta que no se agreguen nuevos hechos.
    Retorna el conjunto final de hechos activados.
    """
    hechos = set(hechos_iniciales)

    while True:
        nuevos_hechos = set()

        for regla in reglas:
            condicion = regla['condicion']
            accion = regla['accion']

            if evaluar_condicion(condicion, variables, hechos):
                if accion not in hechos:
                    nuevos_hechos.add(accion)

        if not nuevos_hechos:
            break  # punto fijo alcanzado

        hechos = hechos | nuevos_hechos

    return hechos



# Analisis estatico



def analisis_estatico(reglas, hechos_activados):
    """
    Revisa las reglas y reporta:
    - Conflictos: misma accion generada por varias reglas
    - Redundancias: reglas con exactamente la misma condicion Y accion
    - Reglas potencialmente inactivas: reglas cuya accion nunca se activo
    """
    mensajes = []


    acciones = {}
    for regla in reglas:
        accion = regla['accion']
        if accion not in acciones:
            acciones[accion] = []
        acciones[accion].append(regla['nombre'])

    for accion, nombres in acciones.items():
        if len(nombres) > 1:

            condiciones = [str(reglas[i]['condicion']) for i in range(len(reglas)) if reglas[i]['nombre'] in nombres]
            if len(set(condiciones)) > 1:
                lista = ', '.join(nombres)
                mensajes.append(f"Action {accion} generated by {lista}")


    grupos = {}
    for regla in reglas:
        clave = (str(regla['condicion']), regla['accion'])
        if clave not in grupos:
            grupos[clave] = []
        grupos[clave].append(regla['nombre'])

    for clave, nombres in grupos.items():
        if len(nombres) > 1:
            lista = ', '.join(nombres)
            mensajes.append(f"Redundant rules: {lista}")


    for regla in reglas:
        if regla['accion'] not in hechos_activados:
            mensajes.append(f"Potentially inactive rule: {regla['nombre']}")

    return mensajes



# Parseo del estado inicial



def parsear_estado(texto_estado):
    """
    Parsea el estado inicial.
    Cada linea puede ser:
      - id = numero   (variable con valor)
      - id            (hecho activo)
    """
    variables = {}
    hechos = set()

    for linea in texto_estado.strip().splitlines():
        linea = linea.strip()
        if not linea:
            continue

        if '=' in linea:
            partes = linea.split('=')
            nombre = partes[0].strip()
            valor = int(partes[1].strip())
            variables[nombre] = valor
        else:
            hechos.add(linea)

    return variables, hechos



# Funcion Principal


def correr_programa(texto_completo):
    """
    Recibe el texto completo del programa (reglas + estado).
    Ejecuta todo el pipeline y muestra el resultado.
    """

    if 'State:' in texto_completo:
        partes = texto_completo.split('State:')
        texto_reglas = partes[0].strip()
        texto_estado = partes[1].strip() if len(partes) > 1 else ''
    else:
        texto_reglas = texto_completo.strip()
        texto_estado = ''


    if texto_reglas:
        tokens = lexer(texto_reglas)
    else:
        tokens = [('EOF', 'EOF')]


    parser = Parser(tokens)
    reglas = parser.parsear_programa()


    variables, hechos_iniciales = parsear_estado(texto_estado)


    hechos_finales = ejecutar_programa(reglas, variables, hechos_iniciales)


    hechos_activados = hechos_finales - hechos_iniciales


    if hechos_activados:
        for hecho in sorted(hechos_activados):
            print(hecho)
    else:
        print("(no output)")


    mensajes = analisis_estatico(reglas, hechos_finales)
    if mensajes:
        print("\nAnalysis:")
        for msg in mensajes:
            print(msg)






def modo_interactivo():
    print("=" * 50)
    print("Interprete de Lenguaje Basado en Reglas")
    print("=" * 50)
    print("Ingresa el programa (reglas + estado).")
    print("Cuando termines, escribe 'FIN' en una linea sola.")
    print("=" * 50)

    lineas = []
    while True:
        linea = input()
        if linea.strip() == 'FIN':
            break
        lineas.append(linea)

    texto = '\n'.join(lineas)
    print("\n--- Resultado ---")
    correr_programa(texto)



# Casos de prueba
# Descomenta el caso que quieras probar


def correr_casos_prueba():
    print("="*50)
    print("CASO 1")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 then alert
State:
temp = 35
""")

    print("\n" + "="*50)
    print("CASO 2")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 then alert
rule r2:
if alert then fan_on
State:
temp = 35
""")

    print("\n" + "="*50)
    print("CASO 3")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 then alert
State:
temp = 20
""")

    print("\n" + "="*50)
    print("CASO 4")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 AND humidity < 50 then alert
State:
temp = 35
humidity = 40
""")

    print("\n" + "="*50)
    print("CASO 5")
    print("="*50)
    correr_programa("""
State:
temp = 35
humidity = 60
""")

    print("\n" + "="*50)
    print("CASO 6 (conflicto)")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 then fan_on
rule r2:
if humidity < 50 then fan_on
State:
temp = 35
humidity = 40
""")

    print("\n" + "="*50)
    print("CASO 7 (redundancia)")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 then alert
rule r2:
if temp > 30 then alert
State:
temp = 35
""")

    print("\n" + "="*50)
    print("CASO 8 (regla inactiva)")
    print("="*50)
    correr_programa("""
rule r1:
if temp > 30 then alert
rule r2:
if alert then fan_on
rule r3:
if humidity < 20 then cooling
State:
temp = 25
humidity = 50
""")

    print("\n" + "="*50)
    print("CASO ADICIONAL (cadena de hechos)")
    print("="*50)
    correr_programa("""
rule r1:
if a then b
rule r2:
if b then c
rule r3:
if c then d
rule r4:
if d then e
State:
a
""")



# Punto de entrada


if __name__ == '__main__':
    print("Selecciona modo:")
    print("  1 - Correr todos los casos de prueba")
    print("  2 - Ingresar programa manualmente")
    opcion = input("Opcion: ").strip()

    if opcion == '1':
        correr_casos_prueba()
    else:
        modo_interactivo()